# setup storage locally for testing purposes
version: '3.5'

services:
  mongo:
    image: mongo:latest
    container_name: url-shortener-mongo
    volumes:
      - redis:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    container_name: url-shortener-redis
    volumes:
      - mongo:/data
    ports:
      - '6379:6379'

volumes:
  mongo:
    name: url-shortener.mongo.data
  redis:
    name: url-shortener.redis.data
