# setup app to test locally
version: '3.5'

services:
  mongo:
    image: mongo:latest
    container_name: url-shortener-mongo
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    container_name: url-shortener-redis
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

  worker:
    image: panda1920/url-shortener-worker:latest
    build:
      context: ./worker/worker
    container_name: url-shortener-worker
    environment:
      - NODE_ENV=development
      - MONGO_HOST=mongo
      - MONGO_USER=mongoadmin
      - MONGO_PASSWORD=password
      - MONGO_AUTHDB=admin
      - REDIS_HOST=redis
      - REDIRECT_DEFAULT_SCHEME=http
      - REDIRECT_DEFAULT_HOST=localhost
      - REDIRECT_DEFAULT_PORT=8888
      - REDIRECT_DEFAULT_PATH=/error
      - SHORTURL_SCHEME=http
      - SHORTURL_HOST=localhost
      - SHORTURL_PORT=8888
      - SHORTURL_PATH=/shorten
    ports:
      - '3001:3000'
    depends_on:
      - mongo
      - redis

  client:
    image: panda1920/url-shortener-client-dev:latest
    build:
      context: ./client
      dockerfile: build/Dockerfile.dev
    container_name: url-shortener-client
    ports:
      - '8888:80'
    depends_on:
      - worker

volumes:
  mongo:
    name: url-shortener.mongo.data
  redis:
    name: url-shortener.redis.data
